server:
  port: 8666
#  servlet:
#    context-path: /uaa

spring:
  application:
    name: authorization-server

  redis:
    host: 118.178.197.5
    database: 5
    password: AliloRedis!@#123
    port: 9763
    pool:
      max-active: 1000
      max-idle: 1
      max-wait: -1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rdsmibifjymbyuqfo.mysql.rds.aliyuncs.com:3306/db_babyting?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: babygo
    password: Boyue123
    type: com.alibaba.druid.pool.DruidDataSource


security:
  oauth2:
    resource:
      filter-order: 3
  basic:
    enabled: false


eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://118.31.54.136:8761/eureka/
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${server.port}
